# Generated by Django 2.2.10 on 2022-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='thumbnailsUrls',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='created',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='publishedDateTime',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video_id',
        ),
        migrations.AddField(
            model_name='videos',
            name='channel_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='channel_subs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_dislike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='channel_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
