# Generated by Django 2.2.10 on 2022-04-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220404_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
