# Generated by Django 2.2.10 on 2022-04-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_videos_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videos',
            name='channel_thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='video_thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
